#!/bin/python

from __future__ import print_function

import sys
import math

def noop(*args):
    pass

def debug(string):
    print("DEBUG >>> {0}".format(string))

debug=noop

def compute_newstyle_devilpoints(input):
    rdp = {} # rank devil points
    wdp = {} # win devil points
    plays = {} # number of games played
    wins = {}  # number of games won
    for game, players in input:
        debug(repr(players))
        numplayers = len(players)
        winscore = max(players.values())
        for player, score in players.items():
            plays[player] = plays.get(player, 0) + 1
            aswell = len([ x for x in players.values() if x >= score])
            aspoor = len([ x for x in players.values() if x <= score])
            rdp[player] = rdp.get(player, 1.0) * aspoor / aswell 
            if score != winscore:
                aswell = numplayers
                aspoor = len([ x for x in players.values() if x < winscore])
            else:
                wins[player] = wins.get(player, 0) + 1
            wdp[player] = wdp.get(player, 1.0) * aspoor / aswell 
    for player in rdp:
        rdp[player] = math.log(rdp[player]) 
        wdp[player] = math.log(wdp[player])
        wins[player] = wins.get(player, 0) 
    return rdp, wdp, plays, wins


def sorted_byval(d):
   def valcmp(x, y):
      return cmp(y[1], x[1])
   i = d.items() 
   i.sort(valcmp)
   return i


if __name__ == '__main__':

    if len(sys.argv) < 2:
        print("Usage: {0[0]} <inputfile>".format(sys.argv))
        sys.exit(1)

    inputfile = sys.argv[1]
    print("Processing {0}...".format(inputfile))
    inputtext = "".join(open(inputfile).readlines())
    input = eval(inputtext)
    debug("input:\n{0!r}".format(input))
    rank, win, plays, wins = compute_newstyle_devilpoints(input)
    totalgamesplayed = len(input)
    players = len(rank)

    print("{0} players played {1} games ".format(players, totalgamesplayed))
    rank = sorted_byval(rank)
    win = sorted_byval(win)
    
    maxnamelen = max([len(entry[0]) for entry in rank])
    fmtstr = ("{rankscore:> 2.4f} " +
        "{rankname:>" + str(maxnamelen) + "s} " +
        "({rankplayed:d}) " +
        "{winscore:> 2.4f} " +
        "{winname:>" + str(maxnamelen) + "s} won " +
        "{winwins:d} of " +
        "{winplayed:d}. ")

    #10+maxnamelen = 7 + 1 + maxnamelen + 1 + 3 + 1 - 4 
    print("Rank"," "*(10+maxnamelen),"Win",sep='')

    for i in range(players):
        rankname = rank[i][0]
        winname = win[i][0]
        info = {
            'rankscore' : rank[i][1],
            'rankname' : rankname,
            'rankplayed' : plays[rankname],
            'winscore' : win[i][1],
            'winname' : winname,
            'winwins' : wins[winname],
            'winplayed' : plays[winname]
        }
        print(fmtstr.format(**info))

